# Generated by Django 3.2.6 on 2021-09-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_category_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="followers",
        ),
    ]
