# Generated by Django 3.2.6 on 2021-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_category_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="Description", max_length=255),
        ),
    ]
