# Generated by Django 3.2.6 on 2021-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
