# Generated by Django 3.2.6 on 2021-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cat_images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
