# Generated by Django 3.2.6 on 2021-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
