# Generated by Django 3.2.6 on 2021-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userprofile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tokens_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tokens_score",
            field=models.IntegerField(default=0),
        ),
    ]
