# Generated by Django 3.2.6 on 2021-09-17 09:42

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0004_auto_20210917_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
