databases:
  - name: content_flow
    databaseName: content_flow
    user: content_flow

services:
  - type: web
    name: content_flow
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn content_flow.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: content_flow
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
